### ISSUE TITLE
not producing any output?

### ISSUE THREAD

**Issue by ddervosj** [s0md3v/Silver#1]
Hello,

Just installed the tool, requirements, nmap & masscan without any issues. Tried running python3 silver.py 127.0.0.1 --quick command (or any other IP/or IP's from file) immediately receiving Scan Completed message:

[~] Deploying masscan
[!] Result saved to /home/xxx/Silver/result-test.txt
[~] 0 services to fingerprint
[!] ETA: 0 seconds 
[~] Spawning 1 nmap instance
[!] Updated /home/xxx/Silver/result-test.txt
[~] Looking for vulnerablilites
[+] Scan completed

~/Silver$ cat result-test.txt 
{}

Any ideas what might be causing this?

Thanks!

**Comment by s0md3v** [comment]
Do you have a firewall?
Have you tried scanning a host that definitely has open ports when scanned with nmap or other port scanners?

**Comment by s0md3v** [comment]
I fixed it, let me know if it still doesn't work for you.

**Comment by ddervosj** [comment]
All fixed. Thanks buddy!
