### ISSUE TITLE
Use masscan only if multiple hosts are provided

### ISSUE THREAD

**Issue by arjunv** [s0md3v/Silver#12]
Usage of masscan against a single host would cause most open ports to be left unidentified, especially at the default rate of 10K.

Instead of asking the user to set the necessary rate (if you add a --rate from another issue here), leave it to nmap to identify open ports, which is much more capable for atleast an entire /24 range, from where usage of masscan would be more useful.

**Comment by jonzatlmi** [comment]
@arjunv do you think nmap would still be suitable for a /24 if you were hitting all 65535 potential ports?  Maybe a better distinction would be when using the -quick flag or not.

**Comment by arjunv** [comment]
Sounds good bro :)

**Comment by s0md3v** [comment]
Sorry bois, can't add this one.
