### ISSUE TITLE
can´t install it

### ISSUE THREAD

**Issue by Besix2** [s0md3v/Silver#22]
Hello,
when I try to inststall it using git clone I get 
`E: Unable to locate package https://github.com/s0md3v
E: Couldn't find any package by glob 'https://github.com/s0md3v'
E: Couldn't find any package by regex 'https://github.com/s0md3v'
`
Thanks for your time

**Comment by meuzgebre** [comment]
@Besix2 Use the following
```
git clone https://github.com/s0md3v/Silver.git
cd Silver
pip3 install -r requirements.txt
```
