### ISSUE TITLE
not scanning the target

### ISSUE THREAD

**Issue by ShUGo95** [s0md3v/Silver#4]
python3 silver.py 127.0.0.1 --quick

It's not scanning the my target ...within seconds it shown scan completed message       

 𝘴𝘪𝘭𝘷𝘦𝘳

[~] Deploying masscan
[!] Result saved to /root/Silver/result-targets.txt
[~] 0 services to fingerprint
[!] ETA: 0 seconds 
[~] Spawning 1 nmap instance
[!] Updated /root/Silver/result-targets.txt
[~] Looking for vulnerablilites
[+] Scan completed
  
please help me out

**Comment by s0md3v** [comment]
This issue has been fixed, re-clone the repository.

**Comment by ShUGo95** [comment]
even though it's raises same issue...

no result in that file

**Comment by s0md3v** [comment]
is it possible for you to share the IP address you are trying to scan?

Message me on twitter [@s0md3v](https://twitter.com/s0md3v) or email me `s0md3v[at]gmail[dot]com`

**Comment by ShUGo95** [comment]
now it's working properly...Thq
