### ISSUE TITLE
Scan immediately ends

### ISSUE THREAD

**Issue by axelarator** [s0md3v/Silver#5]
Using any IP, ETA is always 0 seconds and states there are 0 services to fingerprint. 

On kali, works fine. On manjaro is where the issue is seen

**Comment by assetgrower** [comment]
same here.

**Comment by s0md3v** [comment]
Do you guys have masscan installed?

**Comment by axelarator** [comment]
Yup. Nmap and masscan were installed from AUR

**Comment by assetgrower** [comment]
Yes, in /usr/bin/masscan

**Comment by kirkins** [comment]
I had the issue and I realized it was because I wasn't using `sudo`.

If I use `masscan` directly without using `sudo` I get back:

```
FAIL: wlp3s0: You don't have permission to capture on that device (socket: Operation not permitted)
 [hint] need to sudo or run as root or something
 [hint] I've got some local priv escalation 0days that might work
adapter[wlp3s0].init: failed
```

With Silver the error message was being sent to `/dev/null` so I got success message but ended up with only `{}` in my output folder.

Can anyone with the problem see if using `sudo` fixes the issue?

**Comment by s0md3v** [comment]
@kirkins That's a good lead!

Add the following code to line #73 in `silver.py` and run it again.
```python
print('masscan%s-p%s --rate 10000 -oG %s %s %s >/dev/null 2>&1' % (host, ports_to_scan, savefile, hostfile, exclude)
```
Copy the printed out masscan command and run it with sudo in your terminal and see if masscan works.

**Comment by kirkins** [comment]
@s0md3v I'm sure it works because silver works perfectly fine for me once I use `sudo`. My `result-targets.txt` is as expected once I had the correct permissions.

**Comment by s0md3v** [comment]
Thanks @kirkins :tada: 

I am pushing a patch!

**Comment by s0md3v** [comment]
The root permission thing has been documented and internal checks for dependencies (nmap, masscan, psutil) and the permission itself with pushed soon.

**Comment by slunak** [comment]
> @kirkins That's a good lead!
> 
> Add the following code to line #73 in `silver.py` and run it again.
> 
> ```suggested line```
> 
> Copy the printed out masscan command and run it with sudo in your terminal and see if masscan works.

For everyone who will come here to trouleshoot, this line is missing closing bracket and should be:
```python
print('masscan%s-p%s --rate 10000 -oG %s %s %s >/dev/null 2>&1' % (host, ports_to_scan, savefile, hostfile, exclude))
